export const routes = [
  '/',
  '/fundamentals-of-nursing',
  '/medical-surgical-nursing',
  '/community-health-nursing',
  '/child-health-nursing',
  '/mental-health-nursing',
  '/pharmacology-in-nursing',
  '/infection-control-in-nursing',
  '/hand-hygiene-procedure',
  '/vital-signs-measurement',
  '/nursing-process-steps',
  '/patient-safety-in-nursing',
  '/hand-washing-procedure-who',
  '/injection-procedure-nursing',
  '/blood-pressure-measurement',
  '/iv-infusion-procedure',
  '/importance-of-nursing',
  '/role-of-nurse-in-healthcare',
  '/types-of-nursing-professions'
] as const;
